import type { Metadata } from "next";
import "./globals.css";
import { Syne, Outfit, DM_Sans } from "next/font/google";
import { SmoothScrollbar } from "./components/view/smoothscrollable";
import { GlobalProvider } from "./context/globalcontext";
import { Nav } from "./components/view/nav";
import { Footer } from "./components/view/footer";
import CustomCursor from "./components/customcusor";
import { Loader } from "./components/view/loader";
import { LoadingProvider } from "./context/loadingcontext";
import {Overlay} from "./components/view/overlay"

const outfit = Outfit({
  display: "swap",
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["700", "600", "500", "400"],
});

const dsans = DM_Sans({
  display: "swap",
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["700", "600", "500", "400"],
});

const syne = Syne({
  display: "swap",
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["700", "600", "500", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${dsans.variable} ${syne.variable}`}>
        <SmoothScrollbar>
          <LoadingProvider>
            <GlobalProvider>
              <Loader />
              <Overlay />
              <CustomCursor />
              <Nav />
              {children}
              <Footer />
            </GlobalProvider>
          </LoadingProvider>
        </SmoothScrollbar>
      </body>
    </html>
  );
}
